[package]
name = "poolsummary"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
serde_json = "1"
serde = { version = "1", features = ["derive"] }
clap = { version = "4.5", features = ["derive"] }
monostate = "1"

